language: generic
sudo: required

services:
  - docker

before_install:
  # build an image to run as a test suite
  - docker build -t rkhaskin/react-test -f ./client/Dockerfile.dev ./client

script:
  # run test suite
  - docker run -e CI=true rkhaskin/react-test npm test

after_success:
  - docker build -t rkhaskin/multi-client ./client
  - docker build -t rkhaskin/multi-nginx ./nginx
  - docker build -t rkhaskin/multi-server ./server
  - docker build -t rkhaskin/multi-worker ./worker

  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #push images to docker hub
  - docker push rkhaskin/multi-client
  - docker push rkhaskin/multi-nginx
  - docker push rkhaskin/multi-server
  - docker push rkhaskin/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-687378713160"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
